name: example
description: A sample for page routing code generation.
version: 1.0.0
homepage: https://github.com/bitsydarel/dbpage_routing/example
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  dbpage_routing:
    path: "../"

dev_dependencies:
  build_runner: ^1.10.0
  test: ^1.6.7
  dbpage_routing_generator:
    path: "../dbpage_routing_generator"