name: dbpage_routing
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/bitsydarel/dbpage_routing
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  flutter_code_style:
    git:
      url: git://github.com/bitsydarel/flutter-code-style.git
      ref: v1.6.1
  meta: ^1.1.7