name: dbpage_routing
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/bitsydarel/dbpage_routing
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  test: ^1.6.7

dev_dependencies:
  flutter_code_style: ^1.6.8
  meta: ^1.1.7