name: dbpage_routing_generator
description: dbpage_routing builder, it's generate dart code for page routing
version: 1.0.0
homepage: https://github.com/bitsydarel/dbpage_routing/dbpage_routing_generator
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  source_gen: ^0.9.5
  code_builder: ^3.3.0
  build_config: ^0.4.2
  dbpage_routing:
    path: "../"

dev_dependencies:
  flutter_code_style: ^1.6.8
  test: ^1.0.0
  mockito: ^4.1.0