name: dbpage_routing_generator
description: dbpage_routing builder, it's generate dart code for page routing
version: 1.0.0
homepage: https://github.com/bitsydarel/dbpage_routing/dbpage_routing_generator
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  source_gen: ^0.9.4+3
  code_builder: ^3.2.0

dev_dependencies:
  flutter_code_style:
    git:
      url: git://github.com/bitsydarel/flutter-code-style.git
      ref: v1.6.1
  test: ^1.0.0